### PR TITLE
content: publish STMViewer article

### PR DESCRIPTION
**Pull request by bahildebrand**

### CODE REVIEW

**Review by gminn — APPROVED** [review]

**Comment by klonyyy** [comment]
Hello, would it be possible to replace the images I mentioned in the original PR? I can see they are blurry on the preview and the details are just not readable. I'll prepare new ones ASAP.

**Comment by bahildebrand** [comment]
> Hello, would it be possible to replace the images I mentioned in the original PR? I can see they are blurry on the preview and the details are just not readable. I'll prepare new ones ASAP.

Totally possible! Let me know when you have the new images.

**Comment by klonyyy** [comment]
Got them! Should I make a new fork, or would you like to replace these on your own? 
interrutps
memcpy

**Comment by bahildebrand** [comment]
I can add them. These don't match up 100% with existing pictures. Can you tell me which files these are meant to replace?

**Comment by klonyyy** [comment]
Sure, the first one is interrupts.png, the second one is memcpy.png. Thank you.

**Pull request merged**
