### PR TITLE
Add 2021-02-14-arm-semihosting

### PR DESCRIPTION
**Pull request by ael-mess**
Hi, I've been reading interrupt for a while, and I wanted to participate with this little article about semihosting.

### CODE REVIEW

**Comment by franc0is** [comment]
Merci @ael-mess ! We'll edit this tomorrow and hope to publish it for before the email blast Wednesday. I noticed your author bio was a bit thin, any chance you can add more details in there?

**Comment by tyhoff** [comment]
Starting a review now @ael-mess! Will push some updates as I come across them.

**Comment by tyhoff** [comment]
Awesome post @ael-mess! If you didn't see it, it was posted on Reddit's /r/embedded here: https://old.reddit.com/r/embedded/comments/llyr4m/introduction_to_arm_semihosting/

If you haven't already, we'd also love to have you join the Interrupt Slack group (linked at the top of Interrupt)

**Comment by ael-mess** [comment]
Thank you @tyhoff, I am really glad to participate in Memfault.
I will check the Reddit and Slack group ;)

**Pull request merged**
