### PR TITLE
Guest post on C++17 from Çağlayan Dökme

### PR DESCRIPTION
**Pull request by tyhoff**

### CODE REVIEW

**Comment by tyhoff** [comment]
@CaglayanDokme Let me know if you want any changes made! I'm going to give it one more read-through tomorrow and then ship it on Wednesday.

**Comment by CaglayanDokme** [comment]
@tyhoff Thanks for your time and effort. I'm so happy to be able to be a part of this community. 
I've added a couple of small review notes.

**Comment by tyhoff** [comment]
> Thanks for your time and effort. I'm so happy to be able to be a part of this community.
> I've added a couple of small review notes.

Unfortunately, I can't find your comments - did you start a Review and forget to hit submit?

**Comment by tyhoff** [comment]
> Thanks for your time and effort. I'm so happy to be able to be a part of this community.
> I've added a couple of small review notes.

@CaglayanDokme Unfortunately, I can't find your comments - did you start a Review and forget to hit submit?

**Review by CaglayanDokme — CHANGES_REQUESTED** [review]

**Review by bahildebrand — APPROVED** [review]
Incorporated some of the feedback and did a rebase.

**Pull request merged**
